# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
# version: 2
# updates:
#   - package-ecosystem: "terraform"
#     directory: "/terraform"
#     schedule:
#       interval: "daily" # only on weekdays
#       time: "23:00"
#       timezone: "Europe/Athens"
#     target-branch: "main"
#     open-pull-requests-limit: 3
#     pull-request-branch-name:
#       separator: "/"

#   - package-ecosystem: "github-actions"
#     # Workflow files stored in the default location of `.github/workflows`
#     directory: "/"
#     schedule:
#       interval: "weekly"
#       day: "sunday"
#     target-branch: "main"
#     open-pull-requests-limit: 3
#     pull-request-branch-name:
#       separator: "/"
