name: Daily DevContainer Check

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)

  # You can also trigger this workflow manually
  workflow_dispatch:

jobs:
  python-devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DevContainer CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Spin up Python DevContainer
        run: |
          devcontainer up --workspace-folder . --config .devcontainer/python/devcontainer.json

      # Optional - Run a simple command inside the container to verify
      - name: Verify DevContainer Functionality
        run: |
          devcontainer exec --workspace-folder . --config .devcontainer/python/devcontainer.json python --version

  terraform-devcontainer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install DevContainer CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Spin up Terraform DevContainer
        run: |
          devcontainer up --workspace-folder . --config .devcontainer/terraform/devcontainer.json

      # Optional - Run a simple command inside the container to verify
      - name: Verify DevContainer Functionality
        run: |
          devcontainer exec --workspace-folder . --config .devcontainer/terraform/devcontainer.json terraform --version
